# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f9a2e1e08d5d60b4fadcae20d4d12a3ee197ad64b21f2a5f44e25ba23d8e01bdd62f3e29848b7272cb5ed1119bd85b3c92f8f5bc614cb0569be4f889268f1e83

test:
  secret_key_base: 3dc2d7f90127cee173f508817a86583c3d6221f09d06e43c52f6b29923de024d7a7f71b56103ef68bdea03e44c252b46816ad621393ca7638247e14e9c601602

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
